BASE = "https://statsapi.mlb.com/api/v1"

CLIP_BASE_TEMP = "https://mlb-cuts-diamond.mlb.com/FORGE/{year}/{year}-{month}/{clip_idx}/{playbackID}_1280x720_59_4000K.mp4"

BBREF_BASE = "https://widgets.sports-reference.com/wg.fcgi?site=br&url="

LEAGUES = "100,101,102,103,104,105,106"

LEADER_CATEGORIES = "assists,shutouts,homeRuns,sacrificeBunts,sacrificeFlies,runs,groundoutToFlyoutRatio,stolenBases,battingAverage,groundOuts,numberOfPitches,onBasePercentage,caughtStealing,groundIntoDoublePlays,totalBases,earnedRunAverage,fieldingPercentage,walksAndHitsPerInningPitched,flyouts,hitByPitches,gamesPlayed,walks,sluggingPercentage,onBasePlusSlugging,runsBattedIn,triples,extraBaseHits,hits,atBats,strikeouts,doubles,totalPlateAppearances,intentionalWalks,wins,losses,saves,wildPitch,airOuts,balk,blownSaves,catcherEarnedRunAverage,catchersInterference,chances,completeGames,doublePlays,earnedRun,errors,gamesFinished,gamesStarted,hitBatsman,hitsPer9Inn,holds,innings,inningsPitched,outfieldAssists,passedBalls,pickoffs,pitchesPerInning,putOuts,rangeFactorPerGame,rangeFactorPer9Inn,saveOpportunities,stolenBasePercentage,strikeoutsPer9Inn,strikeoutWalkRatio,throwingErrors,totalBattersFaced,triplePlays,walksPer9Inn,winPercentage"

BIOS_HEADERS = [
        'mlbam',
        'name',
        'nameFirst',
        'nameMiddle',
        'nameLast',
        'nameGiven',
        'nameBoxscore',
        'nameMatrilineal',
        'nickName',
        'birthDate',
        'birthCity',
        'birthStateProvince',
        'birthCountry',
        'age',
        'highschool',
        'college',
        'deathDate',
        'deathCity',
        'deathStateProvince',
        'deathCountry',
        'height',
        'weight',
        'isPlayer',
        'isActive',
        'draftYear',
        'mlbDebutDate',
        # 'mlbDebutTeam',
        'lastGame',
        'recentTeam',
        'bats',
        'throws',
        'primaryNumber',
        'primaryPosition',
        'allNumbers',
        'allPositions',
        'allTeams'
    ]

HITTING_CATEGORIES = [
    'airOuts',
    'atBats',
    'atBatsPerHomeRun',
    'battingAverage',
    'babip',
    'caughtStealing',
    'doubles',
    'extraBaseHits',
    'gamesPlayed',
    'groundIntoDoublePlays',
    'groundOuts',
    'hits',
    'hitsRisp',
    'bitByPitches',
    'homeRuns',
    'homeRunsPerPlateAppearance',
    'intentionalWalks',
    'numberOfPitches',
    'onBasePercentage',
    'onBasePlusSlugging',
    'runs',
    'runsBattedIn',
    'sacrificeBunts',
    'sacrificeFlies',
    'sluggingPercentage',
    'stolenBases',
    'strikeouts',
    'strikeOutsPerPlateAppearance',
    'totalBases',
    'totalPlateAppearances',
    'triples',
    'walksPerStrikeout',
    'walksPerPlateAppearance',
    'walks',
    'walkoffs',
    'streak']

PITCHING_CATEGORIES = [
    'airOuts',
    'balk',
    'qualityStarts',
    'bequeathedRunners',
    'bequeathedRunnersScored',
    'blownSaves',
    'caughtStealing',
    'completeGames',
    'doubles',
    'earnedRun',
    'earnedRunAverage',
    'gamesFinished',
    'gamesPlayed',
    'gamesStarted',
    'groundIntoDoublePlays',
    'groundIntoTriplePlays',
    'groundOuts',
    'hits',
    'hitsRisp',
    'hitBatsman',
    'hitsPer9Inn',
    'holds',
    'homeRuns',
    'homeRunsPerPlateAppearance',
    'inheritedRunner',
    'inheritedRunnerScored',
    'outsPitched',
    'inningsPitched',
    'intentionalWalks',
    'losses',
    'numberOfStrikes',
    'numberOfBalls',
    'numberOfPitches',
    'onBasePercentage',
    'onBasePlusSlugging',
    'pickoffs',
    'pitchesPerInning',
    'pitchesPerPlateAppearance',
    'runs',
    'saves',
    'saveOpportunities',
    'shutouts',
    'sluggingPercentage',
    'stolenBases',
    'stolenBasePercentage',
    'strikeouts',
    'strikeoutsPer9Inn',
    'strikeoutsPerPlateAppearance',
    'totalBases',
    'totalBattersFaced',
    'totalPlateAppearances',
    'triples',
    'walksPerStrikeout',
    'walksPerPlateAppearance',
    'walksAndHitsPerInningPitched',
    'walks',
    'walksPer9Inn',
    'wins',
    'winPercentage']

FIELDING_CATEGORIES = [
    'assists',
    'catchersInterference',
    'caughtStealing',
    'chances',
    'doublePlays',
    'errors',
    'fieldingPercentage',
    'gamesPlayed',
    'gamesStarted',
    'innings',
    'outfieldAssists',
    'passedBalls',
    'putOuts',
    'rangeFactorPerGame',
    'rangeFactorPer9Inn',
    'stolenBases',
    'stolenBasePercentage',
    'throwingErrors',
    'triplePlays']

PITCH_CODES = {
    "EP":"Eephus Pitch",
    "PO":"Pitchout",
    "AB":"Automatic Ball",
    "AS":"Austomatic Strike",
    "CH":"Changeup",
    "CU":"Curveball",
    "FA":"Fastball",
    "FT":"Fastball (Two-seam)",
    "FF":"Fastball (Four-seam)",
    "FC":"Cutter",
    "FS":"Splitter",
    "FO":"Forkball",
    "GY":"Gyroball",
    "KN":"Knuckleball",
    "NP":"No Pitch",
    "SC":"Screwball",
    "SI":"Sinker",
    "SL":"Slider",
    "UN":"Unknown",
    "ST":"Slutter",
    "SV":"Slurve",
    "CS":"Slow Curve"}

ZONE_TOP_STANDARD = 3.65

ZONE_BOTTOM_STANDARD = 1.5

TEAMS = {
    "angels":108,
    "diamondbacks":109,
    "dbacks":109,
    "d-backs":109,
    "braves":144,
    "orioles":110,
    "red sox":111,
    "redsox":111,
    "cubs":112,
    "whitesox":145,
    "white-sox":145,
    "reds":113,
    "indians":114,
    "guardians":114,
    "rockies":115,
    "tigers":116,
    "marlins":146,
    "astros":117,
    "royals":118,
    "dodgers":119,
    "brewers":158,
    "twins":142,
    "mets":121,
    "yankees":147,
    "athletics":133,
    "phillies":143,
    "pirates":134,
    "padres":135,
    "mariners":136,
    "giants":137,
    "cardinals":138,
    "rays":139,
    "devil-rays":139,
    "rangers":140,
    "blue-jays":141,
    "jays":141,
    "nationals":120}

BBREF_SPLITS = {
    "total":"total",
    "plato":"platoon",
    "hmvis":"home_away",
    "half":"half",
    "month":"month",
    "outcb":"outcome",
    "stsub":"start_sub",
    "age":"age",
    "defp":"defensive_position",
    "stad":"game_condition",
    "leado":"leadoff",
    "pitco":"pitch_count",
    "dr":"days_of_rest",
    "lineu":"lineup",
    "tkswg":"take_swing",
    "count":"count",
    "outs":"outs",
    "bases":"bases",
    "clutc":"clutch",
    "innng":"inning",
    "hitlo":"hit_location",
    "traj":"hit_trajectory",
    "oppon":"opponent",
    "ump":"umpire",
    "site":"ballpark"}

BBREF_ENDPOINTS = {
    # PLAYER (YEAR-BY-YEAR)
    'player_batting_standard':"/players/{firstI}/{bbrefID}-bat.shtml&div=div_batting_standard",
    'player_batting_advanced':"/players/{firstI}/{bbrefID}-bat.shtml&div=div_batting_advanced",
    'player_batting_sabermetrics':"/players/{firstI}/{bbrefID}-bat.shtml&div=div_batting_sabermetric",
    'player_batting_ratios':"/players/{firstI}/{bbrefID}-bat.shtml&div=div_batting_ratio",
    'player_batting_situational':"/players/{firstI}/{bbrefID}-bat.shtml&div=div_batting_situational",
    'player_batting_pitches':"/players/{firstI}/{bbrefID}-bat.shtml&div=div_batting_pitches",
    'player_batting_allstar':"/players/{firstI}/{bbrefID}-bat.shtml&div=div_batting_allstar",
    'player_batting_postseason':"/players/{firstI}/{bbrefID}-bat.shtml&div=div_batting_postseason",
    'player_batting_cumulative':"/players/{firstI}/{bbrefID}-bat.shtml&div=div_cumulative_batting",

    'player_pitching_standard':"/players/{firstI}/{bbrefID}-pitch.shtml&div=div_pitching_standard",
    'player_pitching_advanced':"/players/{firstI}/{bbrefID}-pitch.shtml&div=div_pitching_advanced",
    'player_pitching_sabermetrics':"/players/{firstI}/{bbrefID}-pitch.shtml&div=div_pitching_sabermetric",
    'player_pitching_ratios':"/players/{firstI}/{bbrefID}-pitch.shtml&div=div_pitching_ratio",
    'player_pitching_situational':"/players/{firstI}/{bbrefID}-pitch.shtml&div=div_pitching_basesituation",
    'player_pitching_pitches':"/players/{firstI}/{bbrefID}-pitch.shtml&div=div_pitching_pitches",
    'player_pitching_starters':"/players/{firstI}/{bbrefID}-pitch.shtml&div=div_pitching_starter",
    'player_pitching_relievers':"/players/{firstI}/{bbrefID}-pitch.shtml&div=div_pitching_reliever",
    'player_pitching_allstar':"/players/{firstI}/{bbrefID}-pitch.shtml&div=div_pitching_allstar",
    'player_pitching_postseason':"/players/{firstI}/{bbrefID}-pitch.shtml&div=div_pitching_postseason",
    'player_pitching_cumulative':"/players/{firstI}/{bbrefID}-pitch.shtml&div=div_cumulative_pitching",

    'player_fielding_standard':"/players/{firstI}/{bbrefID}-field.shtml&div=div_standard_fielding",
    'player_fielding_appearances':"/players/{firstI}/{bbrefID}-field.shtml&div=div_appearances",
    'player_fielding_sabermetrics':"/players/{firstI}/{bbrefID}-field.shtml&div=div_advanced_fielding",

    'player_splits_batting':"/players/split.fcgi?id={}%26year={}%26t=b&div=div_{}",
    'player_splits_pitching':"/players/split.fcgi?id={}%26year={}%26t=p&div=div_{}",

    # TEAM - PLAYER STATS (SEASON-LEVEL)
    'team_batting_standard_season':"/teams/{tm_bbrefID}/{year}-batting.shtml&div=div_team_batting",
    'team_batting_advanced_season':"/teams/{tm_bbrefID}/{year}-batting.shtml&div=div_players_advanced_batting",
    'team_batting_sabermetrics_season':"/teams/{tm_bbrefID}/{year}-batting.shtml&div=div_players_sabermetric_batting",
    'team_batting_ratios_season':"/teams/{tm_bbrefID}/{year}-batting.shtml&div=div_players_ratio_batting",
    'team_batting_situational_season':"/teams/{tm_bbrefID}/{year}-batting.shtml&div=div_players_situational_batting",
    'team_batting_pitches_season':"/teams/{tm_bbrefID}/{year}-batting.shtml&div=div_players_pitches_batting",
    'team_batting_cumulative':"/teams/{tm_bbrefID}/{year}-batting.shtml&div=div_players_cumulative_batting",

    'team_pitching_standard_season':"/teams/{tm_bbrefID}/{year}-pitching.shtml&div=div_team_pitching",
    'team_pitching_advanced_season':"/teams/{tm_bbrefID}/{year}-pitching.shtml&div=div_players_pitching_advanced",
    'team_pitching_sabermetrics_season':"/teams/{tm_bbrefID}/{year}-pitching.shtml&div=div_players_sabermetric_pitching",
    'team_pitching_ratios_season':"/teams/{tm_bbrefID}/{year}-pitching.shtml&div=div_players_ratio_pitching",
    'team_pitching_situational_season':"/teams/{tm_bbrefID}/{year}-pitching.shtml&div=div_players_basesituation_pitching",
    'team_pitching_pitches_season':"/teams/{tm_bbrefID}/{year}-pitching.shtml&div=div_players_pitches_pitching",
    'team_pitching_starters_season':"/teams/{tm_bbrefID}/{year}-pitching.shtml&div=div_players_starter_pitching",
    'team_pitching_relievers_season':"/teams/{tm_bbrefID}/{year}-pitching.shtml&div=div_players_reliever_pitching",
    'team_pitching_cumulative':"/teams/{tm_bbrefID}/{year}-pitching.shtml&div=div_players_cumulative_pitching",

    'team_fielding_standard_season':"/teams/{tm_bbrefID}/{year}.shtml&div=div_standard_fielding",
    'team_fielding_standard_pos_season':"/teams/{tm_bbrefID}/{year}-fielding.shtml&div=div_players_standard_fielding_{posID}",
    'team_fielding_advanced_pos_season':"/teams/{tm_bbrefID}/{year}-fielding.shtml&div=div_players_advanced_fielding_{posID}",

    'team_baserunning_season':"/teams/{tm_bbrefID}/{year}-batting.shtml&div=div_players_baserunning_batting",

    # TEAM - PLAYER STATS (ALL)
    'team_batting_alumni':"/teams/{tm_bbrefID}/bat.shtml&div=div_batting_register",
    'team_pitching_alumni':"/teams/{tm_bbrefID}/pitch.shtml&div=div_pitching_register",

    # TEAM - TEAM STATS (YEAR-BY-YEAR)
    'team_batting_yby':"/teams/{tm_bbrefID}/batteam.shtml&div=div_yby_team_bat",
    'team_batting_yby_rankings':"/teams/{tm_bbrefID}/batteam.shtml&div=div_yby_team_bat_ranks",

    # TEAM - TEAM STATS (SEASON-LEVEL)
    'team_splits_batting':"/teams/split.cgi?t=b%26team={tm_bbrefID}%26year={year}&div=div_{split_type}",
    'team_splits_pitching':"/teams/split.cgi?t=p%26team={tm_bbrefID}%26year={year}&div=div_{split_type}",


    # TEAM - MISC
    'team_past_names':"/teams/{tm_bbrefID}/&div=div_history",
    'team_history_yby':"/teams/{tm_bbrefID}/&div=div_franchise_years",
    'team_hof_players':"/teams/{tm_bbrefID}/hof.shtml&div=div_hof",
    'team_attendance_yby':"/teams/{tm_bbrefID}/attend.shtml&div=div_franchise_years",

    'team_gamelogs_batting':"/teams/tgl.cgi?team={tm_bbrefID}%26t=b%26year={year}&div=div_team_batting_gamelogs",
    'team_gamelogs_pitching':"/teams/tgl.cgi?team={tm_bbrefID}%26t=p%26year={year}&div=div_team_pitching_gamelogs",
    'team_daily_lineups':"/teams/{tm_bbrefID}/{year}-lineups.shtml&div=div_grid_table_495491",
    'team_batting_orders':"/teams/{tm_bbrefID}/{year}-batting-orders.shtml&div=div_grid_table_867096",
    'team_roster_40man':"/teams/{tm_bbrefID}/{year}-roster.shtml&div=div_the40man",
    'team_roster_full':"/teams/{tm_bbrefID}/{year}-roster.shtml&div=div_appearances",

    ## (FOR 'leagueID', the entire MLB is represented by the 'MLB' ID value *EXCEPT* for Split Stat Tables)
    # LEAGUE - PLAYER STATS (SEASON-LEVEL)
    'league_batting_standard_players':"/leagues/{leagueID}/{year}-standard-batting.shtml&div=div_players_standard_batting",
    'league_batting_advanced_players':"/leagues/{leagueID}/{year}-advanced-batting.shtml&div=div_players_advanced_batting",
    'league_batting_sabermetrics_player':"/leagues/{leagueID}/{year}-sabermetric-batting.shtml&div=div_players_sabermetric_batting",
    'league_batting_ratios_players':"/leagues/{leagueID}/{year}-ratio-batting.shtml&div=div_players_ratio_batting",
    'league_batting_situational_players':"/leagues/{leagueID}/{year}-situational-batting.shtml&div=div_players_situational_batting",
    'league_batting_pitches_players':"/leagues/{leagueID}/{year}-pitches-batting.shtml&div=div_players_pitches_batting",
    'league_batting_cumulative_players':"/leagues/majors/{year}-cumulative-batting.shtml&div=div_players_cumulative_batting",

    'league_pitching_standard_players':"/leagues/{leagueID}/2021-standard-pitching.shtml&div=div_players_standard_pitching",
    'league_pitching_advanced_players':"/leagues/{leagueID}/2021-advanced-pitching.shtml&div=div_players_advanced_pitching",
    'league_pitching_ratios_players':"/leagues/{leagueID}/{year}-ratio-pitching.shtml&div=div_players_ratio_pitching",
    'league_pitching_situational_players':"/leagues/{leagueID}/{year}-basesituation-pitching.shtml&div=div_players_basesituation_pitching",
    'league_pitching_pitches_players':"/leagues/{leagueID}/{year}-pitches-pitching.shtml&div=div_players_pitches_pitching",
    'league_pitching_starter_players':"/leagues/{leagueID}/{year}-starter-pitching.shtml&div=div_players_starter_pitching",
    'league_pitching_reliever_players':"/leagues/{leagueID}/{year}-reliever-pitching.shtml&div=div_players_reliever_pitching",
    'league_pitching_cumulative_players':"/leagues/majors/{year}-cumulative-pitching.shtml&div=div_players_cumulative_pitching",

    'league_fielding_players':"/leagues/{leagueID}/{year}-standard-fielding.shtml&div=div_players_players_standard_fielding_fielding",
    'league_appearances_players':"/leagues/{leagueID}/{year}-appearances-fielding.shtml&div=div_players_players_appearances_fielding",
    'league_fielding_pos_standard_players':"/leagues/{leagueID}/{year}-specialpos_{posID}-fielding.shtml&div=div_players_players_standard_fielding_fielding",
    'league_fielding_pos_advanced_players':"/leagues/{leagueID}/{year}-specialpos_{posID}-fielding.shtml&div=div_players_players_advanced_fielding_{posID}_fielding",

    'league_running_players':"/leagues/{leagueID}/{year}-baserunning-batting.shtml&div=div_players_baserunning_batting",

    # LEAGUE - TEAM STATS (SEASON-LEVEL)
    'league_batting_standard_teams':"/leagues/{leagueID}/{year}-standard-batting.shtml&div=div_teams_standard_batting",
    'league_batting_advanced_teams':"/leagues/{leagueID}/{year}-advanced-batting.shtml&div=div_teams_advanced_batting",
    'league_batting_sabermetrics_teams':"/leagues/{leagueID}/{year}-sabermetric-batting.shtml&div=div_teams_sabermetric_batting",
    'league_batting_ratios_teams':"/leagues/{leagueID}/{year}-ratio-batting.shtml&div=div_teams_ratio_batting",
    'league_batting_situational_teams':"/leagues/{leagueID}/{year}-situational-batting.shtml&div=div_teams_situational_batting",
    'league_batting_pitches_teams':"/leagues/{leagueID}/{year}-pitches-batting.shtml&div=div_teams_pitches_batting",

    'league_pitching_standard_teams':"/leagues/{leagueID}/{year}-standard-pitching.shtml&div=div_teams_standard_pitching",
    'league_pitching_advanced_teams':"/leagues/{leagueID}/{year}-advanced-pitching.shtml&div=div_teams_advanced_pitching",
    'league_pitching_ratios_teams':"/leagues/{leagueID}/{year}-ratio-pitching.shtml&div=div_teams_ratio_pitching",
    'league_pitching_situational_teams':"/leagues/{leagueID}/{year}-basesituation-pitching.shtml&div=div_teams_basesituation_pitching",
    'league_pitching_pitches_teams':"/leagues/{leagueID}/{year}-pitches-pitching.shtml&div=div_teams_pitches_pitching",
    'league_pitching_starter_teams':"/leagues/{leagueID}/{year}-starter-pitching.shtml&div=div_teams_starter_pitching",
    'league_pitching_reliever_teams':"/leagues/{leagueID}/{year}-reliever-pitching.shtml&div=div_teams_reliever_pitching",

    'league_fielding_teams':"/leagues/{leagueID}/{year}-standard-fielding.shtml&div=div_teams_standard_fielding",
    'league_appearances_teams':"/leagues/{leagueID}/{year}-appearances-fielding.shtml&div=div_teams_appearances",
    'league_fielding_pos_standard_teams':"/leagues/{leagueID}/{year}-specialpos_{posID}-fielding.shtml&div=div_teams_standard_fielding",
    'league_fielding_pos_advanced_teams':"/leagues/{leagueID}/{year}-specialpos_{posID}-fielding.shtml&div=div_teams_advanced_fielding_{posID}",

    'league_running_teams':"/leagues/{leagueID}/{year}-baserunning-batting.shtml&div=div_teams_baserunning_batting",

    'league_batsplits_season_totals':"/leagues/split.cgi?t=b&lg={leagueID}&year={year}&div=div_{split_type}",
    'league_pitsplits_season_totals':"/leagues/split.cgi?t=p&lg={leagueID}&year={year}&div=div_{split_type}",


    # LEAGUE - LEAGUE STATS
    'league_batting_yby_totals':"/leagues/{leagueID}/bat.shtml&div=div_teams_standard_batting_totals",
    'league_batting_yby_averages':"/leagues/{leagueID}/bat.shtml&div=div_teams_standard_batting",
    'league_pitching_yby_totals':"/leagues/{leagueID}/pitch.shtml&div=div_teams_standard_pitching_totals",
    'league_pitching_yby_averages':"/leagues/{leagueID}/pitch.shtml&div=div_teams_standard_pitching",
    'league_fielding_yby_totals':"/leagues/{leagueID}/field.shtml&div=div_teams_standard_fielding_totals",
    'league_fielding_yby_averages':"/leagues/{leagueID}/field.shtml&div=div_teams_standard_fielding",

    # SPECIFIC SPLITS
    'teams_batsplits':"/tools/split_stats_lg.cgi?full=0&params={split_type}|{split_entry}|ML|{year}|bat|AB",
    'teams_pitsplits':"/tools/split_stats_lg.cgi?full=0&params={split_type}|{split_entry}|ML|{year}|pitch|AB|",

    # STANDINGS
    'standings_overall':"/leagues/majors/2021-standings.shtml&div=div_expanded_standings_overall",
    'standings_divisions':"/leagues/{leagueID}/{year}-standings.shtml&div=div_expanded_standings_{div}", # div = 'wild_card' for Wild Card Standings

    # HOME RUN LOGS
    'hr_log_batter':"/players/event_hr.fcgi?id={batter}%26t=b&div=div_play_by_play",
    'hr_log_pitcher':"/players/event_hr.fcgi?id={pitcher}%26t=p&div=div_play_by_play",

    # MANAGERS
    'manager_stats':"/leagues/{leagueID}/{year}-managers.shtml&div=div_manager_record",
    'manager_tendencies':"/leagues/{leagueID}/{year}-managers.shtml&div=div_manager_tendencies",

    # LEADERS (TEAM LEVEL)
    'leaders_batting_career_team':'/teams/{tm_bbrefID}/leaders_bat_50.shtml&div=career_leaderboard_{stat}',
    'leaders_batting_season_team':'/teams/{tm_bbrefID}/leaders_bat_50_season.shtml&div=season_leaderboard_{stat}',
    'leaders_pitching_career_team':'/teams/{tm_bbrefID}/leaders_pitch_50.shtml&div=career_leaderboard_{stat}',
    'leaders_pitching_season_team':'/teams/{tm_bbrefID}/leaders_pitch_50_season.shtml&div=season_leaderboard_{stat}'

    # LEADERS (LEAGUE LEVEL)

    # LEADERS (ALL-TIME)
    }

STAT_GROUPS = "hitting,pitching,fielding,catching,running"

LEADERS_SEASON = "/stats/leaders?statType=season&leaderCategories={statCategories}&leaderGameTypes={gameTypes}&statGroup={statGroups}&season={season}&playerPool={playerPool}&limit=1000"

LEADERS_ALLTIME_SINGLE_SEASON = "/stats/leaders?statType=statsSingleSeason&leaderCategories={statCategories}&leaderGameTypes={gameTypes}&statGroup={statGroups}&playerPool={playerPool}&limit=1000"

LEADERS_ALLTIME_CAREER = "/stats/leaders?statType=career&leaderCategories={statCategories}&leaderGameTypes={gameTypes}&statGroup={statGroups}&playerPool={playerPool}"

LEADERS_TEAM_SEASON = "/stats/leaders?statType=season&leaderCategories={statCategories}&leaderGameTypes={gameTypes}&statGroup={statGroups}&season={season}&playerPool={playerPool}&teamId={teamId}&limit=1000"

LEADERS_TEAM_ALLTIME_SINGLE_SEASON = "/stats/leaders?statType=statsSingleSeason&leaderCategories={statCategories}&leaderGameTypes={gameTypes}&statGroup={statGroups}&playerPool={playerPool}&teamId={teamId}&limit=1000"

LEADERS_TEAM_ALLTIME_CAREER = "/stats/leaders?statType=career&leaderCategories={statCategories}&leaderGameTypes={gameTypes}&statGroup={statGroups}&playerPool={playerPool}&teamId={teamId}&limit=1000"

# teams_cols = 'yearID,fullName,lgAbbrv,locationName,clubName,mlbam,franchID,bbrefID,retroID,mlbID,fileCode,venueName,venue_mlbam,firstYear'

# people_cols = 'yearID,fullName,lgAbbrv,locationName,clubName,mlbam,franchID,bbrefID,retroID,mlbID,fileCode,venueName,venue_mlbam,firstYear'

POSITION_DICT = {
    1:"P",
    2:"C",
    3:"1B",
    4:"2B",
    5:"3B",
    6:"SS",
    7:"LF",
    8:"CF",
    9:"RF"}

bbref_splits_dict = {
    "season":"Season",
    "platoon":"Platoon",
    "hmvis":"Home or Away",
    "half":"Pre/Post All-Star Game",
    "month":"Monthly",
    "outcome":"Outcome",
    "stsub":"Starter/Substitute",
    "age":"Player Age",
    "defp":"Defensive Positions",
    "leadoff":"Leading Off Inning",
    "bop":"Batting Order",
    "count":"Count",
    "outs":"Number of Outs",
    "bases":"Situation/Bases Occupied",
    "clutch":"Clutch",
    "leverage":"Leverage",
    "inning":"Inning",
    "timesfacingopp":"Pitching Matchup",
    "power":"Pitcher Type",
    "gbfbpitch":"Ground Ball/Fly Ball Pitchers",
    "hitloc":"Hit Location",
    "traj":"Trajectory",
    "opp":"Opponents",
    "conditions":"Playing Conditions",
    "parks":"Stadiums",
    "platparks":"Stadium | Platoon",

    "seasonex":"Season (measured at Game-Level)",
    "platoong":"Platoon (by Events)",
    "hmvisex":"Home or Away (measured at Game-Level)",
    "halfex":"Pre/Post All-Star Game (measured at Game-Level)",
    "monthex":"Monthly (measured at Game-Level)",
    "outcomeex":"Outcome (measured at Game-Level)",
    "sprel":"Pitcher Role","sprelex":"Pitcher Role (measured at Game-Level)",
    "ageex":"Player Age (measured at Game-Level)",
    "rs":"Run Support","rsex":"Run Support (measured at Game-Level)",
    "lineup":"Batting Order",
    "takeswing":"First Pitch - Take or Swing",
    "defpos":"Opponents Defensive Position",
    "pitchcount":"Pitch Count",
    "dr":"Days Rested","drex":"Days Rested (measured at Game-Level)",
    "oppex":"Opponents (measured at Game-Level)",
    "conditionsex":"Playing Conditions (measured at Game-Level)",
    "parksex":"Stadiums (measured at Game-Level)",
    "platparks":"Stadiums | Platoon (measured at Game-Level)",
    "catcher":"Catchers",
    "ump":"Umpires","umpex":"Umpires (measured at Game-Level)"}

tuplelist = [
            ('diamondbacks','Arizona Diamondbacks'),
            ('braves',      'Atlanta Braves'),
            ('orioles',     'Baltimore Orioles'),
            ('red-sox',     'Boston Red Sox'),
            ('cubs',        'Chicago Cubs'),
            ('white-sox',   'Chicago White Sox'),
            ('reds',        'Cincinnati Reds'),
            ('indians',     'Cleveland Guardians (Indians)'),
            ('rockies',     'Colorado Rockies'),
            ('tigers',      'Detroit Tigers'),
            ('astros',      'Houston Astros'),
            ('royals',      'Kansas City Royals'),
            ('angels',      'Los Angeles Angels'),
            ('dodgers',     'Los Angeles Dodgers'),
            ('marlins',     'Miami Marlins'),
            ('brewers',     'Milwaukee Brewers'),
            ('twins',       'Minnesota Twins'),
            ('mets',        'New York Mets'),
            ('yankees',     'New York Yankees'),
            ('athletics',   'Oakland Athletics'),
            ('phillies',    'Philadelphia Phillies'),
            ('pirates',     'Pittsburgh Pirates'),
            ('padres',      'San Diego Padres'),
            ('giants',      'San Francisco Giants'),
            ('mariners',    'Seattle Mariners'),
            ('cardinals',   'St. Louis Cardinals'),
            ('rays',        'Tampa Bay Rays'),
            ('rangers',     'Texas Rangers'),
            ('blue-jays',   'Toronto Blue Jays'),
            ('nationals',   'Washington Nationals')
            ]

teamcolors = {
    'diamondbacks':     ['#A71930','#B09F71'],
    'braves':           ['#CE1141','#13274F'],
    'orioles':          ['#DF4601','#000000'],
    'red-sox':          ['#BD3039','#0C2340'],
    'cubs':             ['#0E3386','#CC3433'],
    'white-sox':        ['#13120F','#41414'],
    'reds':             ['#C6011F','#000000'],
    'indians':          ['#0C2340','#E31937'],
    'rockies':          ['#33006F','#949da2'],
    'tigers':           ['#0C2340','#FA4616'],
    'astros':           ['#002D62','#EB6E1F'],
    'royals':           ['#004687','#BD9B60'],
    'angels':           ['#003263','#BA0021'],
    'dodgers':          ['#005A9C','#EF3E42'],
    'marlins':          ['#00A3E0','#EF3340'],
    'brewers':          ['#FFC52F','#12284B'],
    'twins':            ['#002B5C','#D31145'],
    'mets':             ['#002D72','#FF5910'],
    'yankees':          ['#003087','#E4002C'],
    'athletics':        ['#003831','#EFB21E'],
    'phillies':         ['#E81828','#002D72'],
    'pirates':          ['#27251F','#cc8a00'],
    'cardinals':        ['#C41E3A','#0C2340'],
    'padres':           ['#002D62','#cc8a00'],
    'giants':           ['#FD5A1E','#27251F'],
    'mariners':         ['#0C2C56','#005C5C'],
    'rays':             ['#092C5C','#81a8ce'],
    'rangers':          ['#003278','#C0111F'],
    'blue-jays':        ['#134A8E','#1D2D5C'],
    'nationals':        ['#AB0003','#14225A']}

STATDICT = {
            'gamesPlayed':"G",
            'atBats':"AB",
            'position':'pos',
            'Pos':'pos',
            'plateAppearances':"PA",
            'hits':"H",
            'runs':"R",
            'doubles':"2B",
            'triples':"3B",
            'homeRuns':"HR",
            'rbi':"RBI",
            'strikeOuts':"SO",
            'baseOnBalls':"BB",
            'intentionalWalks':"IBB",
            'groundOuts':"GO",
            'airOuts':"AO",
            'groundOutsToAirouts':"GO/AO",
            'gidp':"GIDP",
            'groundIntoDoublePlay':"GIDP",
            'groundIntoTriplePlay':"GITP",
            'gidpOpp':"GIDPO",
            'hitByPitch':"HBP",
            'avg':"AVG",
            'obp':"OBP",
            'slg':"SLG",
            'ops':"OPS",
            'babip':"BABIP",
            'caughtStealing':"CS",
            'stolenBases':"SB",
            'stolenBasePercentage':"SB%",
            'numberOfPitches':"P",
            'totalBases':"TB",
            'leftOnBase':"LOB",
            'sacBunts':"sB",
            'sacFlies':"sF",
            'catchersInterference':"CI",
            'atBatsPerHomeRun':"AB/HR",
            "extraBaseHits":"exBH",
            "pitchesPerPlateAppearance":"P/PA",
            "walksPerPlateAppearance":"BB/PA",
            "strikeoutsPerPlateAppearance":"SO/PA",
            "homeRunsPerPlateAppearance":"HR/PA",
            "walksPerStrikeout":"BB/SO",
            "iso":"ISO",
            "reachedOnError":"ROE",
            "walkOffs":"WO",
            "flyOuts":"FO",
            "popOuts":"PO",
            "lineOuts":"LO",
            "totalSwings":"TS",
            "swingAndMisses":"Whiffs",
            "ballsInPlay":"BIP",
            "groundHits":"GH",
            "flyHits":"FH",
            "popHits":"PH",
            "lineHits":"LH",
            "pickoffs":"PK",
            "hitBatsmen":"HB",
            "completeGames":"CG",
            "shutouts":"ShO",
            "strikes":"K",
            "balls":"B",
            "whip":"WHIP",
            "balks":"BK",
            "inningsPitched":"IP",
            "wins":"W",
            "losses":"L",
            "saves":"SV",
            "saveOpportunities":"SVO",
            "era":"ERA",
            "holds":"HLD",
            "blownSaves":"BS",
            "earnedRuns":"ER",
            "battersFaced":"BF",
            "gamesPitched":"GP",
            "strikePercentage":"K%",
            "wildPitches":"WP",
            "passedBall":"PB",
            "winPercentage":"W%",
            "pitchesPerInning":"P/Inn",
            "strikeoutWalkRatio":"SO:BB",
            "strikesoutsToWalks":"SO:BB",
            "strikeoutsPer9Inn":"SO/9",
            "strikeoutsPer9":"SO/9",
            "walksPer9Inn":"BB/9",
            "walksPer9":"BB/9",
            "baseOnBallsPer9":"BB/9",
            "hitsPer9Inn":"H/9",
            "hitsPer9":"H/9",
            "runsScoredPer9":"R/9",
            "homeRunsPer9":"HR/9",
            "inheritedRunners":"IR",
            "inheritedRunnersScored":"IRS",
            "qualityStarts":"QS",
            "runSupport":"RS",
            "gamesStarted":"GS",
            "outs":"O",
            "gamesFinished":"GF",
            "games":"G",
            "innings":"INNs",
            "putOuts":"PO",
            "assists":"A",
            "errors":"E",
            "chances":"Ch",
            "fielding":"FLD%",
            "rangeFactorPerGame":"RF/G",
            "rangeFactorPer9Inn":"RF/9",
            "doublePlays":"DP",
            "triplePlays":"TP",
            "throwingErrors":"thE",
            "catcherERA":"cERA",
            "PA":"PA",
            "AB":"AB",
            "R":"R",
            "H":"H",
            "2B":"2B",
            "3B":"3B",
            "HR":"HR",
            "RBI":"RBI",
            "BB":"BB",
            "IBB":"IBB",
            "SO":"SO",
            "HBP":"HBP",
            "SH":"sB",
            "SF":"sF",
            "ROE":"ROE",
            "GIDP":"GIDP",
            "SB":"SB",
            "CS":"CS",
            "batting_avg":"AVG",
            "onbase_perc":"OBP",
            "slugging_perc":"SLG",
            "onbase_plus_slugging":"OBP",
            "LOB":"LOB",
            "team_game_num":"Gm#",
            "date_game":"Date",
            "team_homeORaway":"",
            "opp_ID":"Opp",
            "game_result":"Result",
            'seasonId':'Season',
            'hasWildcard':'Wild Card',
            'preSeasonStartDate':'Pre-Season Start',
            'preSeasonEndDate':'Pre-Season End',
            'regularSeasonStartDate':'Regular Season Start',
            'regularSeasonEndDate':'Regular Season End',
            'lastDate1stHalf':'1st Half End',
            'firstDate2ndHalf':'2nd Half Start',
            'allStarDate':'All-Star Game',
            'postSeasonStartDate':'Post-Season Start',
            'postSeasonEndDate':'Post-Season End',
            'seasonStartDate':'Season Start',
            'seasonEndDate':'Season End',
            "season":"season",
            "runsScored":"R",
            "runsAllowed":"RA",
            "runDifferential":"RunDiff",
            "leagueRank":"Rank (Lg)",
            "divisionRank":"Rank (Div)",
            "divisionGamesBack":"Div GB",
            "leagueGamesBack":"Lg GB",
            "sportGamesBack":"GB",
            "League":"Lg",
            "Division":"Div",
            "bequeathedRunners":"BQ",
            "bequeathedRunnersScored":"BQS",
            103:"AL",
            104:"NL",
            200:"AL West",
            201:"AL East",
            202:"AL Central",
            203:"NL West",
            204:"NL East",
            205:"NL Central",
            "winningPercentage":"W%",
            "fullName":"Team",
            "lgAbbrv":"Lg/Div",
            "manager":"Manager(s)",
            "GP":"G",
            "career_game_num":"Career Gm#",
            "team_game_num":"Season Gm#",
            "player_game_span":"Play Span",
            "team_ID":"Team",
            "batting_order_position":"BOP",
            "pos_game":"Pos",
            "inherited_runners":"IR",
            "inherited_score":"IS",
            "inplay_gb_total":"GB",
            "inplay_fb_total":"FB",
            "inplay_ld":"LD",
            "inplay_pu":"PU",
            "Inn_def":"Inns.",
            "E_def":"E",
            "chances":"Ch",
            "DP_def":"DP",
            "strikes_total":"K",
            "strikes_looking":"K (Lk)",
            "strikes_swinging":"K (Sw)",
            "batters_faced":"BF",
            "days_rest":"DR",
            "earned_run_avg":"ERA",
            "pitches":"Pitch Ct",
            "split_group":"split_group",
            'season':"season",
            'tm_mlbam':"tm_mlbam",
            'tm_name':"tm_name", 
            'tm_bbrefID':"tm_bbrefID",
            'lg_mlbam':"lg_mlbam",
            'lg_abbrv':"League",
            'div_mlbam':"div_mlbam",
            'div_short':"Division",
            'v_mlbam':"v_mlbam",
            'G':"G", 
            'W':"W", 
            'L':"L", 
            'W%':"W%", 
            'R':"R", 
            'RA':"RA", 
            'RunDiff':"Rdiff",
            'vAL':"vAL",
            'vNL':"vNL",
            'vWest':"vWest", 
            'vEast':"vEast",
            'vCentral':"vCentral", 
            'Home':"Home",
            'Away':"Away",
            'vRHP':"vRHP",
            'vLHP':"vLHP",
            'Last10':"Last10",
            'ExInns':"ExInns",
            'OneRun':"OneRun",
            'Winners':"Winners",
            'Day':"Day",
            'Night':"Night",
            'Grass':"Grass",
            'Turf':"Turf",
            "home":"Home",
            "away":"Away",
            "last10":"Last10",
            "exInns":"ExInns",
            "oneRun":"OneRun",
            "winners":"Win",
            "day":"Day",
            "night":"Night",
            "grass":"Grass",
            "turf":"Turf",
            "runDiff":"R.Diff",
            "season":"season",
            "Season":"season",
            "player":"player",
            "Player":"player",
            "player_mlbam":"player_mlbam",
            "player_id":"player_mlbam",
            "Team":"team",
            "team":"team",
            "team_mlbam":"team_mlbam",
            "team_id":"team_mlbam",
            "league":"league",
            "lg":"league",
            "league_mlbam":"league_mlbam",
            "league_id":"league_mlbam",
            "game_type":"game_type",
            "gameType":"game_type",
            "event":"event_type",
            "event_type":"event_type",
            "eventType":"eventType"
            }

COLS_HIT = [
    'G',
    'AB',
    'PA',
    'H',
    'R',
    '2B',
    '3B',
    'HR',
    'RBI',
    'SO',
    'BB',
    'IBB',
    'GO',
    'AO',
    'GO/AO',
    'HBP',
    'AVG',
    'OBP',
    'SLG',
    'OPS',
    'BABIP',
    'CS',
    'SB',
    'SB%',
    'GIDP',
    'P',
    'TB',
    'LOB',
    'CI',
    'AB/HR',
    'sB',
    'sF',
    ]
COLS_HIT_ADV = [
    'PA',
    'TB',
    'LOB',
    'BIP',
    'BABIP',
    'exBH',
    'HBP',
    'GIDP',
    'GIDPO',
    'P',
    'P/PA',
    'BB/PA',
    'SO/PA',
    'HR/PA',
    'BB/SO',
    'ISO',
    'ROE',
    'WO',
    'FO',
    'TS',
    'Whiffs',
    'PO',
    'LO',
    'GO',
    'FH',
    'PH',
    'LH',
    'GH',
    'sB',
    'sF',
    ]
COLS_PIT = [
    'G',
    'GP',
    'GS',
    'GF',
    'ERA',
    'P',
    'IP',
    'W',
    'L',
    'WHIP',
    'SO',
    'GO',
    'AO',
    'H',
    'R',
    '2B',
    '3B',
    'HR',
    'BB',
    'IBB',
    'HBP',
    'AB',
    'AVG',
    'OBP',
    'SLG',
    'OPS',
    'CS',
    'SB',
    'SB%',
    'GIDP',
    'SV',
    'SVO',
    'HLD',
    'CG',
    'ShO',
    'BS',
    'ER',
    'BF',
    'O',
    'K',
    'K%',
    'HB',
    'BK',
    'WP',
    'PK',
    'TB',
    'GO/AO',
    'W%',
    'P/Inn',
    'SO:BB',
    'SO/9',
    'BB/9',
    'H/9',
    'R/9',
    'HR/9',
    'IR',
    'IRS',
    'CI',
    'sB',
    'sF',
    ]
COLS_PIT_ADV = [
    'W%',
    'BF',
    'BABIP',
    'OBP',
    'SLG',
    'OPS',
    'H/9',
    'R/9',
    'SO/9',
    'BB/9',
    'HR/9',
    'SO:BB',
    'IR',
    'IRS',
    'BQ',
    'BQS',
    'SB',
    'CS',
    'WP',
    'QS',
    'GF',
    '2B',
    '3B',
    'GIDP',
    'GIDPO',
    'BK',
    'PK',
    'TS',
    'Whiffs',
    'BIP',
    'RS',
    'K%',
    'P/Inn',
    'P/PA',
    'BB/PA',
    'SO/PA',
    'HR/PA',
    'BB/SO',
    'ISO',
    'FO',
    'PO',
    'LO',
    'GO',
    'FH',
    'PH',
    'LH',
    'GH',
    ]
COLS_FLD = [
    'pos',
    'G',
    'GS',
    'INNs',
    'PO',
    'A',
    'E',
    'Ch',
    'DP',
    'TP',
    'FLD%',
    'thE',
    'RF/G',
    'RF/9',
    ]
W_SEASON = ['season','game_type','tm_mlbam','tm_name','lg_mlbam','lg_name']
WO_SEASON = ['game_type','tm_mlbam','tm_name','lg_mlbam','lg_name']

BAT_FIELDS = [
    'gamesPlayed',
    'atBats',
    'plateAppearances',
    'hits',
    'runs',
    'doubles',
    'triples',
    'homeRuns',
    'rbi',
    'strikeOuts',
    'baseOnBalls',
    'intentionalWalks',
    'groundOuts',
    'airOuts',
    'groundOutsToAirouts',
    'hitByPitch',
    'avg',
    'obp',
    'slg',
    'ops',
    'babip',
    'caughtStealing',
    'stolenBases',
    'stolenBasePercentage',
    'numberOfPitches',
    'totalBases',
    'leftOnBase',
    'sacBunts',
    'sacFlies',
    'catchersInterference',
    'atBatsPerHomeRun']

BAT_FIELDS_ADV = [
    "totalSwings",
    "swingAndMisses",
    "ballsInPlay",
    "extraBaseHits",
    "gidp",
    "gidpOpp",
    "pitchesPerPlateAppearance",
    "walksPerPlateAppearance",
    "strikeoutsPerPlateAppearance",
    "homeRunsPerPlateAppearance",
    "walksPerStrikeout",
    "iso",
    "reachedOnError",
    "walkOffs",
    "groundOuts",
    "flyOuts",
    "popOuts",
    "lineOuts",
    "groundHits",
    "flyHits",
    "popHits",
    "lineHits"
]

PITCH_FIELDS = [
    'gamesPitched',
    'gamesStarted',
    'gamesFinished',
    'hits',
    'runs',
    'earnedRuns',
    'doubles',
    'triples',
    'homeRuns',
    'strikeOuts',
    'baseOnBalls',
    'intentionalWalks',
    'era',
    'whip',
    'inningsPitched',
    'numberOfPitches',
    'atBats',
    'battersFaced',
    'hitByPitch',
    'wins',
    'losses',
    'winPercentage',
    'completeGames',
    'shutouts',
    'saves',
    'saveOpportunities',
    'blownSaves',
    'holds',
    'avg',
    'obp',
    'slg',
    'ops',
    'caughtStealing',
    'stolenBases',
    'stolenBasePercentage',
    'outs',
    'groundOuts',
    'airOuts',
    'groundOutsToAirouts',
    'groundIntoDoublePlay',
    'strikes',
    'strikePercentage',
    'balks',
    'wildPitches',
    'pickoffs',
    'totalBases',
    'sacBunts',
    'sacFlies',
    'pitchesPerInning',
    'strikeoutWalkRatio',
    'strikeoutsPer9Inn',
    'walksPer9Inn',
    'hitsPer9Inn',
    'runsScoredPer9',
    'homeRunsPer9',
    'catchersInterference',
    'inheritedRunners',
    'inheritedRunnersScored']
PITCH_FIELDS_ADV = [
    'babip',
    'qualityStarts',
    'gidp',
    'gidpOpp',
    'totalSwings',
    'swingAndMisses',
    'ballsInPlay',
    'runSupport',
    'pitchesPerPlateAppearance',
    'walksPerPlateAppearance',
    'strikeoutsPerPlateAppearance',
    'homeRunsPerPlateAppearance',
    'walksPerStrikeout',
    'iso',
    'groundOuts',
    'flyOuts',
    'popOuts',
    'lineOuts',
    'groundHits',
    'flyHits',
    'popHits',
    'lineHits']
FIELD_FIELDS = [
    "games",
    "gamesStarted",
    "innings",
    "putOuts",
    "assists",
    "errors",
    "chances",
    "throwingErrors",
    "rangeFactorPerGame",
    "rangeFactorPer9Inn",
    "doublePlays",
    "triplePlays",
    "fielding"]

YBY_BAT_FIELDS = [
    'gamesPlayed',
    'atBats',
    'plateAppearances',
    'hits',
    'runs',
    'doubles',
    'triples',
    'homeRuns',
    'rbi',
    'strikeOuts',
    'baseOnBalls',
    'intentionalWalks',
    'atBatsPerHomeRun',
    'hitByPitch',
    'avg',
    'obp',
    'slg',
    'ops',
    'sacBunts',
    'sacFlies']

YBY_BAT_FIELDS_ADV = [
    'totalSwings',
    'swingAndMisses',
    'babip',
    'gidp',
    'gidpOpp',
    'leftOnBase',
    'extraBaseHits',
    'flyOuts',
    'popOuts',
    'lineOuts',
    'groundHits',
    'flyHits',
    'popHits',
    'lineHits']

YBY_PITCH_FIELDS = [
    'gamesPitched',
    'wins',
    'losses',
    'winPercentage',
    'completeGames',
    'shutouts',
    'saves',
    'atBats',
    'hits',
    'doubles',
    'triples',
    'homeRuns',
    'runs',
    'earnedRuns',
    'strikeOuts',
    'baseOnBalls',
    'intentionalWalks',
    'era',
    'whip',
    'inningsPitched',
    'numberOfPitches',
    'caughtStealing',
    'stolenBases',
    'stolenBasePercentage',
    'strikes',
    'strikePercentage',
    'wildPitches']

YBY_PITCH_FIELDS_ADV = [
    'totalSwings',
    'swingAndMisses',
    'groundOuts',
    'flyOuts',
    'popOuts',
    'lineOuts',
    'groundHits',
    'flyHits',
    'popHits',
    'lineHits']

YBY_FIELD_FIELDS = [
    "games",
    "gamesStarted",
    "innings",
    "putOuts",
    "assists",
    "errors",
    "chances",
    "throwingErrors",
    "rangeFactorPerGame",
    "rangeFactorPer9Inn",
    "doublePlays",
    "triplePlays",
    "fielding"]
  
ybyPerformance_fields = [
    "gamesPlayed",
    "wins",
    "losses",
    "winningPercentage",
    "runsScored",
    "runsAllowed",
    "runDifferential",
    "leagueRank",
    "divisionRank"]

staff_dict = {
    'Assistant Catching Coach': 'Coaches',
    'Assistant Catching Coordinator': 'Coordinators',
    'Assistant Coach': 'Coaches',
    'Assistant Hitting Coach': 'Hitting Staff',
    'Assistant Hitting Coordinator': 'Coordinators',
    'Assistant Manager': 'Managers',
    'Assistant Pitching Coach': 'Pitching Staff',
    'Assistant Pitching Coordinator': 'Coordinators',
    'Associate Manager': 'Managers',
    'Batting Coach': 'Hitting Staff',
    'Bench Coach': 'Coaches',
    'Bullpen Assistant': 'Pitching Staff',
    'Bullpen Catcher': 'Pitching Staff',
    'Bullpen Coach': 'Pitching Staff',
    'Bullpen Coordinator': 'Coordinators',
    'Catching Coach': 'Coaches',
    'Catching Coordinator':'Coordinators',
    'Defensive Coach': 'Coaches',
    'First Base Coach': 'First Base Coaches',
    'Fundamentals Coach': 'Coaches',
    'Head Coach': 'Coaches',
    'Hitting Coach': 'Hitting Staff',
    'Hitting Consultant': 'Hitting Staff',
    'Hitting Coordinator': 'Coordinators',
    'Infield Coach': 'Coaches',
    'Interim Bullpen Coach': 'Pitching Staff',
    'Interim Hitting Coach': 'Hitting Staff',
    'Interim Manager': 'Managers',
    'Interim Pitching Coach': 'Pitching Staff',
    'Manager': 'Managers',
    'Pitching Coach': 'Pitching Staff',
    'Pitching Consultant': 'Pitching Staff',
    'Pitching Coordinator': 'Coordinators',
    'Quality Control Coach': 'Coaches',
    'Third Base Coach': 'Third Base Coaches',
    'Analytics Coordinator':'Miscellaneous',
    'Quality Control Coach':'Miscellaneous',
    'First Base':'First Base Coaches',
    'Third Base':'Third Base Coaches',
    'Game Planning Coordinator':'Miscellaneous'
    }
ybyPerf_invites = (
    'records,teams,id,season,teamName,league,name,division,record,divisionRank,leagueRank,wildCardRank,sportRank,gamesPlayed,gamesBack,wildCardGamesBack,leagueGamesBack,sportGamesBack,divisionGamesBack,conferenceGamesBack,records,splitRecords,wins,losses,type,pct,divisionRecords,overallRecords,leagueRecords,runsAllowed,runsScored,runDifferential,winningPercentage,venue')

divIDs = {
    200:"AL West",
    201:"AL East",
    202:"AL Central",
    203:"NL West",
    204:"NL East",
    205:"NL Central"
}

LEAGUE_IDS_SHORT = {
    200:"West",
    201:"East",
    202:"Central",
    203:"West",
    204:"East",
    205:"Central",
    103:"AL",
    104:"NL"
}
leagueIDs = {
    "100":"AA",
    "101":"UA",
    "102":"NA",
    "103":"AL",
    "104":"NL",
    "105":"PL",
    "106":"FL",
    "AA":"American Association",
    "UA":"Union Association",
    "NA":"National Association",
    "AL":"American League",
    "NL":"National League",
    "PL":"Players League",
    "FL":"Federal League",
    "200":"AL West",
    "201":"AL East",
    "202":"AL Central",
    "203":"NL West",
    "204":"NL East",
    "205":"NL Central",
    "AL West":"American League West",
    "AL East":"American League East",
    "AL Central":"American League Central",
    "NL West":"National League West",
    "NL East":"National League East",
    "NL Central":"National League Central",}

LEAGUE_IDS = leagueIDs

teamIDs_all = (
    "108,109,110,111,112,113,114,115,116,117,118,119,120,121,123,124,125,126,127,128,129,130,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,150,151,152,153,155,156,157,158,161,163,165,166,167,168,169,172,173,174,175,176,177,178,180,181,184,185,186,187,188,189,191,192,193,195,196,197,198,199,200,201,202,204,205,206,208,209,210,211,212,213,219,220,221,222,223,224,297,298,299")

bbref_hit_log_fields = (
    "career_game_num",
    "team_game_num",
    "date_game",
    "team_ID",
    "team_homeORaway",
    "opp_ID",
    "game_result",
    "player_game_span",
    "batting_order_position",
    "PA",
    "AB",
    "R",
    "H",
    "2B",
    "3B",
    "HR",
    "RBI",
    "BB",
    "IBB",
    "SO",
    "HBP",
    "SH",
    "SF",
    "GIDP",
    "SB",
    "CS",
    "batting_avg",
    "onbase_perc",
    "slugging_perc",
    "onbase_plus_slugging",
    "pos_game"
)
bbref_pitch_log_fields = (
    "career_game_num",
    "team_game_num",
    "date_game",
    "team_ID",
    "team_homeORaway",
    "opp_ID",
    "game_result",
    "player_game_span",
    "days_rest",
    "IP",
    "H",
    "R",
    "ER",
    "BB",
    "SO",
    "HR",
    "HBP",
    "earned_run_avg",
    "batters_faced",
    "pitches",
    "strikes_total",
    "strikes_looking",
    "strikes_swinging",
    "inplay_gb_total",
    "inplay_fb_total",
    "inplay_ld",
    "inplay_pu",
    "inherited_runners",
    "inherited_score",
    "SB",
    "CS",
    "pickoffs",
    "AB",
    "2B",
    "3B",
    "IBB",
    "GIDP",
    "SF"
)
bbref_field_log_fields = (
    "team_game_num",
    "date_game",
    "team_homeORaway",
    "opp_ID",
    "game_result",
    "player_game_span",
    "batters_faced",
    "Inn_def",
    "PO",
    "A",
    "E_def",
    "chances",
    "DP_def",
    "pos_game"
)

# SITUATION CODES
GAME = ["h","a","d","n","g","t"]
MONTHS = ["3","4","5","6","7","8","9","10","11"]
MATCHUP = ["l","r","vl","vr"]
SCORE = ["sah","sbh","sti"]
RESULTS = ["twn","tls","taw","tal"]
BATTING_ORDER = ["b1","b2","b3","b4","b5","b6","b7","b8","b9","lo"]
INNINGS = ["i01","i02","i03","i04","i05","i06","i07","i08","i09","ix"]
RUNNERS_ON = ["e","r0","r1","r2","r3","r12","r23","r123","ron","ron2","risp","risp2"]
OUTS = ["o0","o1","o2"]
COUNT = ["fp","ac","bc","ec","2s","fc","c00","c01","c02","c10","c11","c12","c20","c21","c22","c30","c31","c32"]

SIT_CODES = "h,a,d,n,g,t,3,4,5,6,7,8,9,10,11,l,r,vl,vr,sah,sbh,sti,twn,tls,taw,tal,b1,b2,b3,b4,b5,b6,b7,b8,b9,lo,i01,i02,i03,i04,i05,i06,i07,i08,i09,ix,e,r0,r1,r2,r3,r12,r23,r123,ron,ron2,risp,risp2,o0,o1,o2,fp,ac,bc,ec,2s,fc,c00,c01,c02,c10,c11,c12,c20,c21,c22,c30,c31,c32"

SIT_DICT = {
    'fp':(1,"First Pitch"),
    'ac':(2,"Ahead in Count"),
    'bc':(3,"Behind in Count"),
    'ec':(4,"Even Count"),
    '2s':(5,"Two Strikes"),
    'fc':(6,"Full Count"),
    'c00':(7,"0-0 Count"),
    'c01':(8,"0-1 Count"),
    'c02':(9,"0-2 Count"),
    'c10':(10,"1-0 Count"),
    'c11':(11,"1-1 Count"),
    'c12':(12,"1-2 Count"),
    'c20':(13,"2-0 Count"),
    'c21':(14,"2-1 Count"),
    'c22':(15,"2-2 Count"),
    'c30':(16,"3-0 Count"),
    'c31':(17,"3-1 Count"),
    'c32':(18,"3-2 Count"),
    'h':(1,"Home Games"),
    'a':(2,"Away Games"),
    'd':(3,"Day Games"),
    'n':(4,"Night Games"),
    'g':(5,"On Grass"),
    't':(6,"On Turf"),
    "vl":(1,"vs LHP"),
    "vr":(2,"vs RHP"),
    'l':(3,"Batting Left"),
    'r':(4,"Batting Right"),
    'sah':(1,"Team is ahead"),
    'sbh':(2,"Team is behind"),
    'sti':(3,"Game is tied"),
    'twn':(1,"Team Wins"),
    'tls':(2,"Team Loses"),
    'taw':(3,"Following Team Win"),
    'tal':(4,"Following Team Loss"),
    'lo':(0,"Leadoff"),
    'b1':(1,"Batting 1st"),
    'b2':(2,"Batting 2nd"),
    'b3':(3,"Batting 3rd"),
    'b4':(4,"Batting 4th"),
    'b5':(5,"Batting 5th"),
    'b6':(6,"Batting 6th"),
    'b7':(7,"Batting 7th"),
    'b8':(8,"Batting 8th"),
    'b9':(9,"Batting 9th"),
    'ph':(10,"Pinch Hitter"),
    'ix':(10,"Extra Innings"),
    'i01':(1,"1st Inning"),
    'i02':(2,"2nd Inning"),
    'i03':(3,"3rd Inning"),
    'i04':(4,"4th Inning"),
    'i05':(5,"5th Inning"),
    'i06':(6,"6th Inning"),
    'i07':(7,"7th Inning"),
    'i08':(8,"8th Inning"),
    'i09':(9,"9th Inning"),
    'e':(0,"Bases Empty (not leadoff)"),
    'r0':(1,"Bases Empty"),
    'r1':(2,"Runner on 1st"),
    'r2':(3,"Runner on 2nd"),
    'r3':(4,"Runner on 3rd"),
    'r12':(5,"Runners on 1st & 2nd"),
    'r23':(6,"Runners on 2nd & 3rd"),
    'r123':(7,"Bases Loaded"),
    'ron':(8,"Runners On"),
    'ron2':(9,"Runners On, 2 Outs"),
    'risp':(10,"RISP"),
    'risp2':(11,"RISP, 2 Outs"),
    'o0':(0,"No Outs"),
    'o1':(1,"1 Out"),
    'o2':(2,"2 Outs")}

sitCodes = "[h,a,d,n,g,t,3,4,5,6,7,8,9,10,11,l,r,vl,vr,sah,sbh,sti,twn,tls,taw,tal,b1,b2,b3,b4,b5,b6,b7,b8,b9,lo,i01,i02,i03,i04,i05,i06,i07,i08,i09,ix,e,r0,r1,r2,r3,r12,r23,r123,ron,ron2,risp,risp2,o0,o1,o2,fp,ac,bc,ec,2s,fc,c00,c01,c02,c10,c11,c12,c20,c21,c22,c30,c31,c32]"

sitFields = "people,stats,type,displayName,group,splits,season,stat,gamesPlayed,groundOuts,airOuts,doubles,triples,homeRuns,strikeOuts,baseOnBalls,intentionalWalks,hits,hitByPitch,avg,atBats,obp,slg,ops,groundIntoDoublePlay,groundIntoTriplePlay,numberOfPitches,plateAppearances,totalBases,rbi,leftOnBase,sacBunts,sacFlies,babip,groundOutsToAirouts,catchersInterference,atBatsPerHomeRun,split,code,description"

bat_leader_stats = {
    "WAR":"WAR_def",
    "AVG":"batting_avg",
    "OBP":"onbase_perc",
    "GP":"G",
    "AB":"AB",
    "PA":"PA",
    "R":"R",
    "H":"H",
    "TB":"TB",
    "2B":"2B",
    "3B":"3B",
    "HR":"HR",
    "RBI":"RBI",
    "BB":"BB",
    "SO":"SO",
    "SB":"SB",
    "1B":"1B",
    "OPS":"onbase_plus_slugging_plus",
    "RC":"RC",
    "XBH":"XBH",
    "TOB":"TOB",
    "Offensive Win %":"offensive_winning_perc",
    "HBP":"HBP"
    }

NETWORKS = {
    
}

